language: python

python:
 - "3.6"
 
cache: pip
dist: xenial

install: 
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda env update -q -y --file environment.yml

script:
  - flake8 --exit-zero ./pyseus
  - pylint --exit-zero ./pyseus
  - pytest --ignore=tests/test_core.py --ignore=tests/test_tools.py
