language: python

python:
 - "3.6"
 
cache: pip
dist: xenial

install: pip install -r requirements.txt

script:
  - flake8 --exit-zero ./pyseus
  - pylint --exit-zero ./pyseus
  - pytest --ignore=tests/test_core.py --ignore=tests/test_tools.py
